//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Flux authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHTTPScalingSet) DeepCopyInto(out *ClusterHTTPScalingSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHTTPScalingSet.
func (in *ClusterHTTPScalingSet) DeepCopy() *ClusterHTTPScalingSet {
	if in == nil {
		return nil
	}
	out := new(ClusterHTTPScalingSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterHTTPScalingSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterHTTPScalingSetList) DeepCopyInto(out *ClusterHTTPScalingSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterHTTPScalingSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterHTTPScalingSetList.
func (in *ClusterHTTPScalingSetList) DeepCopy() *ClusterHTTPScalingSetList {
	if in == nil {
		return nil
	}
	out := new(ClusterHTTPScalingSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterHTTPScalingSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConcurrencyMetricSpec) DeepCopyInto(out *ConcurrencyMetricSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConcurrencyMetricSpec.
func (in *ConcurrencyMetricSpec) DeepCopy() *ConcurrencyMetricSpec {
	if in == nil {
		return nil
	}
	out := new(ConcurrencyMetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Conditions) DeepCopyInto(out *Conditions) {
	{
		in := &in
		*out = make(Conditions, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in Conditions) DeepCopy() Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPInterceptorConfigurationSpec) DeepCopyInto(out *HTTPInterceptorConfigurationSpec) {
	*out = *in
	if in.ProxyPort != nil {
		in, out := &in.ProxyPort, &out.ProxyPort
		*out = new(int32)
		**out = **in
	}
	if in.AdminPort != nil {
		in, out := &in.AdminPort, &out.AdminPort
		*out = new(int32)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(string)
		**out = **in
	}
	if in.HeaderTimeout != nil {
		in, out := &in.HeaderTimeout, &out.HeaderTimeout
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(string)
		**out = **in
	}
	if in.IdleConnTimeout != nil {
		in, out := &in.IdleConnTimeout, &out.IdleConnTimeout
		*out = new(string)
		**out = **in
	}
	if in.TLSHandshakeTimeout != nil {
		in, out := &in.TLSHandshakeTimeout, &out.TLSHandshakeTimeout
		*out = new(string)
		**out = **in
	}
	if in.ExpectContinueTimeout != nil {
		in, out := &in.ExpectContinueTimeout, &out.ExpectContinueTimeout
		*out = new(string)
		**out = **in
	}
	if in.ForceHTTP2 != nil {
		in, out := &in.ForceHTTP2, &out.ForceHTTP2
		*out = new(bool)
		**out = **in
	}
	if in.KeepAlive != nil {
		in, out := &in.KeepAlive, &out.KeepAlive
		*out = new(string)
		**out = **in
	}
	if in.MaxIdleConns != nil {
		in, out := &in.MaxIdleConns, &out.MaxIdleConns
		*out = new(int)
		**out = **in
	}
	if in.PollingInterval != nil {
		in, out := &in.PollingInterval, &out.PollingInterval
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPInterceptorConfigurationSpec.
func (in *HTTPInterceptorConfigurationSpec) DeepCopy() *HTTPInterceptorConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPInterceptorConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPInterceptorScalingSpec) DeepCopyInto(out *HTTPInterceptorScalingSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPInterceptorScalingSpec.
func (in *HTTPInterceptorScalingSpec) DeepCopy() *HTTPInterceptorScalingSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPInterceptorScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPInterceptorSpec) DeepCopyInto(out *HTTPInterceptorSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(HTTPInterceptorConfigurationSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(HTTPInterceptorScalingSpec)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPInterceptorSpec.
func (in *HTTPInterceptorSpec) DeepCopy() *HTTPInterceptorSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPInterceptorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPSalingSetTargetRef) DeepCopyInto(out *HTTPSalingSetTargetRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPSalingSetTargetRef.
func (in *HTTPSalingSetTargetRef) DeepCopy() *HTTPSalingSetTargetRef {
	if in == nil {
		return nil
	}
	out := new(HTTPSalingSetTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPScaledObject) DeepCopyInto(out *HTTPScaledObject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPScaledObject.
func (in *HTTPScaledObject) DeepCopy() *HTTPScaledObject {
	if in == nil {
		return nil
	}
	out := new(HTTPScaledObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPScaledObject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPScaledObjectCondition) DeepCopyInto(out *HTTPScaledObjectCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPScaledObjectCondition.
func (in *HTTPScaledObjectCondition) DeepCopy() *HTTPScaledObjectCondition {
	if in == nil {
		return nil
	}
	out := new(HTTPScaledObjectCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPScaledObjectList) DeepCopyInto(out *HTTPScaledObjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPScaledObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPScaledObjectList.
func (in *HTTPScaledObjectList) DeepCopy() *HTTPScaledObjectList {
	if in == nil {
		return nil
	}
	out := new(HTTPScaledObjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPScaledObjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPScaledObjectSpec) DeepCopyInto(out *HTTPScaledObjectSpec) {
	*out = *in
	if in.ScalingSet != nil {
		in, out := &in.ScalingSet, &out.ScalingSet
		*out = new(HTTPSalingSetTargetRef)
		**out = **in
	}
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PathPrefixes != nil {
		in, out := &in.PathPrefixes, &out.PathPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ScaleTargetRef = in.ScaleTargetRef
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(ReplicaStruct)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetPendingRequests != nil {
		in, out := &in.TargetPendingRequests, &out.TargetPendingRequests
		*out = new(int32)
		**out = **in
	}
	if in.CooldownPeriod != nil {
		in, out := &in.CooldownPeriod, &out.CooldownPeriod
		*out = new(int32)
		**out = **in
	}
	if in.ScalingMetric != nil {
		in, out := &in.ScalingMetric, &out.ScalingMetric
		*out = new(ScalingMetricSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPScaledObjectSpec.
func (in *HTTPScaledObjectSpec) DeepCopy() *HTTPScaledObjectSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPScaledObjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPScaledObjectStatus) DeepCopyInto(out *HTTPScaledObjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(Conditions, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPScaledObjectStatus.
func (in *HTTPScaledObjectStatus) DeepCopy() *HTTPScaledObjectStatus {
	if in == nil {
		return nil
	}
	out := new(HTTPScaledObjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPScalerConfigurationSpec) DeepCopyInto(out *HTTPScalerConfigurationSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPScalerConfigurationSpec.
func (in *HTTPScalerConfigurationSpec) DeepCopy() *HTTPScalerConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPScalerConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPScalerSpec) DeepCopyInto(out *HTTPScalerSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPScalerSpec.
func (in *HTTPScalerSpec) DeepCopy() *HTTPScalerSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPScalingSet) DeepCopyInto(out *HTTPScalingSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPScalingSet.
func (in *HTTPScalingSet) DeepCopy() *HTTPScalingSet {
	if in == nil {
		return nil
	}
	out := new(HTTPScalingSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPScalingSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPScalingSetList) DeepCopyInto(out *HTTPScalingSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPScalingSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPScalingSetList.
func (in *HTTPScalingSetList) DeepCopy() *HTTPScalingSetList {
	if in == nil {
		return nil
	}
	out := new(HTTPScalingSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPScalingSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPScalingSetSpec) DeepCopyInto(out *HTTPScalingSetSpec) {
	*out = *in
	in.Interceptor.DeepCopyInto(&out.Interceptor)
	in.Scaler.DeepCopyInto(&out.Scaler)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPScalingSetSpec.
func (in *HTTPScalingSetSpec) DeepCopy() *HTTPScalingSetSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPScalingSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPScalingSetStatus) DeepCopyInto(out *HTTPScalingSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPScalingSetStatus.
func (in *HTTPScalingSetStatus) DeepCopy() *HTTPScalingSetStatus {
	if in == nil {
		return nil
	}
	out := new(HTTPScalingSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateMetricSpec) DeepCopyInto(out *RateMetricSpec) {
	*out = *in
	out.Window = in.Window
	out.Granularity = in.Granularity
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateMetricSpec.
func (in *RateMetricSpec) DeepCopy() *RateMetricSpec {
	if in == nil {
		return nil
	}
	out := new(RateMetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicaStruct) DeepCopyInto(out *ReplicaStruct) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int32)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicaStruct.
func (in *ReplicaStruct) DeepCopy() *ReplicaStruct {
	if in == nil {
		return nil
	}
	out := new(ReplicaStruct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleTargetRef) DeepCopyInto(out *ScaleTargetRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleTargetRef.
func (in *ScaleTargetRef) DeepCopy() *ScaleTargetRef {
	if in == nil {
		return nil
	}
	out := new(ScaleTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingMetricSpec) DeepCopyInto(out *ScalingMetricSpec) {
	*out = *in
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(ConcurrencyMetricSpec)
		**out = **in
	}
	if in.Rate != nil {
		in, out := &in.Rate, &out.Rate
		*out = new(RateMetricSpec)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingMetricSpec.
func (in *ScalingMetricSpec) DeepCopy() *ScalingMetricSpec {
	if in == nil {
		return nil
	}
	out := new(ScalingMetricSpec)
	in.DeepCopyInto(out)
	return out
}
