/*
Copyright The Flagger Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/stefanprodan/flagger/pkg/apis/flagger/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CanaryDeploymentLister helps list CanaryDeployments.
type CanaryDeploymentLister interface {
	// List lists all CanaryDeployments in the indexer.
	List(selector labels.Selector) (ret []*v1beta1.CanaryDeployment, err error)
	// CanaryDeployments returns an object that can list and get CanaryDeployments.
	CanaryDeployments(namespace string) CanaryDeploymentNamespaceLister
	CanaryDeploymentListerExpansion
}

// canaryDeploymentLister implements the CanaryDeploymentLister interface.
type canaryDeploymentLister struct {
	indexer cache.Indexer
}

// NewCanaryDeploymentLister returns a new CanaryDeploymentLister.
func NewCanaryDeploymentLister(indexer cache.Indexer) CanaryDeploymentLister {
	return &canaryDeploymentLister{indexer: indexer}
}

// List lists all CanaryDeployments in the indexer.
func (s *canaryDeploymentLister) List(selector labels.Selector) (ret []*v1beta1.CanaryDeployment, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.CanaryDeployment))
	})
	return ret, err
}

// CanaryDeployments returns an object that can list and get CanaryDeployments.
func (s *canaryDeploymentLister) CanaryDeployments(namespace string) CanaryDeploymentNamespaceLister {
	return canaryDeploymentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// CanaryDeploymentNamespaceLister helps list and get CanaryDeployments.
type CanaryDeploymentNamespaceLister interface {
	// List lists all CanaryDeployments in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1beta1.CanaryDeployment, err error)
	// Get retrieves the CanaryDeployment from the indexer for a given namespace and name.
	Get(name string) (*v1beta1.CanaryDeployment, error)
	CanaryDeploymentNamespaceListerExpansion
}

// canaryDeploymentNamespaceLister implements the CanaryDeploymentNamespaceLister
// interface.
type canaryDeploymentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CanaryDeployments in the indexer for a given namespace.
func (s canaryDeploymentNamespaceLister) List(selector labels.Selector) (ret []*v1beta1.CanaryDeployment, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.CanaryDeployment))
	})
	return ret, err
}

// Get retrieves the CanaryDeployment from the indexer for a given namespace and name.
func (s canaryDeploymentNamespaceLister) Get(name string) (*v1beta1.CanaryDeployment, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("canarydeployment"), name)
	}
	return obj.(*v1beta1.CanaryDeployment), nil
}
