apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger
spec:
  template:
    spec:
      containers:
        - name: flagger
          args:
            - -log-level=debug
            - -include-label-prefix=app.kubernetes.io
            - -mesh-provider=gatewayapi:v1alpha2
            - -metrics-server=http://flagger-prometheus:9090
