sudo: required
language: go

go:
- 1.12.x

services:
- docker

addons:
  apt:
    packages:
    - docker-ce

#before_script:
#  - go get -u sigs.k8s.io/kind
#  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
#  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/

script:
  - set -e
  - make test-fmt
  - make test-codegen
  - go test -race -coverprofile=coverage.txt -covermode=atomic $(go list ./pkg/...)
  - make build

after_success:
- if [ -z "$DOCKER_USER" ]; then
    echo "PR build, skipping image push";
  else
    BRANCH_COMMIT=${TRAVIS_BRANCH}-$(echo ${TRAVIS_COMMIT} | head -c7);
    docker tag weaveworks/flagger:latest quay.io/weaveworks/flagger:${BRANCH_COMMIT};
    echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin quay.io;
    docker push quay.io/weaveworks/flagger:${BRANCH_COMMIT};
  fi
- if [ -z "$TRAVIS_TAG" ]; then
    echo "Not a release, skipping image push";
  else
    docker tag weaveworks/flagger:latest quay.io/weaveworks/flagger:${TRAVIS_TAG};
    echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin quay.io;
    docker push quay.io/weaveworks/flagger:$TRAVIS_TAG;
  fi
- bash <(curl -s https://codecov.io/bash)
- rm coverage.txt

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
