apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: test
  labels:
      env: production
      test: label
spec:
  type: LoadBalancer
  selector:
      app: podinfo
  ports:
  - name: http
    port: 9898
    protocol: TCP
    targetPort: http
