/*
Copyright 2020 The Flux authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/fluxcd/flagger/pkg/apis/http/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterHTTPScalingSetLister helps list ClusterHTTPScalingSets.
// All objects returned here must be treated as read-only.
type ClusterHTTPScalingSetLister interface {
	// List lists all ClusterHTTPScalingSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterHTTPScalingSet, err error)
	// ClusterHTTPScalingSets returns an object that can list and get ClusterHTTPScalingSets.
	ClusterHTTPScalingSets(namespace string) ClusterHTTPScalingSetNamespaceLister
	ClusterHTTPScalingSetListerExpansion
}

// clusterHTTPScalingSetLister implements the ClusterHTTPScalingSetLister interface.
type clusterHTTPScalingSetLister struct {
	indexer cache.Indexer
}

// NewClusterHTTPScalingSetLister returns a new ClusterHTTPScalingSetLister.
func NewClusterHTTPScalingSetLister(indexer cache.Indexer) ClusterHTTPScalingSetLister {
	return &clusterHTTPScalingSetLister{indexer: indexer}
}

// List lists all ClusterHTTPScalingSets in the indexer.
func (s *clusterHTTPScalingSetLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterHTTPScalingSet, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterHTTPScalingSet))
	})
	return ret, err
}

// ClusterHTTPScalingSets returns an object that can list and get ClusterHTTPScalingSets.
func (s *clusterHTTPScalingSetLister) ClusterHTTPScalingSets(namespace string) ClusterHTTPScalingSetNamespaceLister {
	return clusterHTTPScalingSetNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ClusterHTTPScalingSetNamespaceLister helps list and get ClusterHTTPScalingSets.
// All objects returned here must be treated as read-only.
type ClusterHTTPScalingSetNamespaceLister interface {
	// List lists all ClusterHTTPScalingSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterHTTPScalingSet, err error)
	// Get retrieves the ClusterHTTPScalingSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ClusterHTTPScalingSet, error)
	ClusterHTTPScalingSetNamespaceListerExpansion
}

// clusterHTTPScalingSetNamespaceLister implements the ClusterHTTPScalingSetNamespaceLister
// interface.
type clusterHTTPScalingSetNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ClusterHTTPScalingSets in the indexer for a given namespace.
func (s clusterHTTPScalingSetNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterHTTPScalingSet, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterHTTPScalingSet))
	})
	return ret, err
}

// Get retrieves the ClusterHTTPScalingSet from the indexer for a given namespace and name.
func (s clusterHTTPScalingSetNamespaceLister) Get(name string) (*v1alpha1.ClusterHTTPScalingSet, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("clusterhttpscalingset"), name)
	}
	return obj.(*v1alpha1.ClusterHTTPScalingSet), nil
}
