/*
Copyright 2020 The Flux authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/fluxcd/flagger/pkg/apis/http/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// HTTPScaledObjectLister helps list HTTPScaledObjects.
// All objects returned here must be treated as read-only.
type HTTPScaledObjectLister interface {
	// List lists all HTTPScaledObjects in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.HTTPScaledObject, err error)
	// HTTPScaledObjects returns an object that can list and get HTTPScaledObjects.
	HTTPScaledObjects(namespace string) HTTPScaledObjectNamespaceLister
	HTTPScaledObjectListerExpansion
}

// hTTPScaledObjectLister implements the HTTPScaledObjectLister interface.
type hTTPScaledObjectLister struct {
	listers.ResourceIndexer[*v1alpha1.HTTPScaledObject]
}

// NewHTTPScaledObjectLister returns a new HTTPScaledObjectLister.
func NewHTTPScaledObjectLister(indexer cache.Indexer) HTTPScaledObjectLister {
	return &hTTPScaledObjectLister{listers.New[*v1alpha1.HTTPScaledObject](indexer, v1alpha1.Resource("httpscaledobject"))}
}

// HTTPScaledObjects returns an object that can list and get HTTPScaledObjects.
func (s *hTTPScaledObjectLister) HTTPScaledObjects(namespace string) HTTPScaledObjectNamespaceLister {
	return hTTPScaledObjectNamespaceLister{listers.NewNamespaced[*v1alpha1.HTTPScaledObject](s.ResourceIndexer, namespace)}
}

// HTTPScaledObjectNamespaceLister helps list and get HTTPScaledObjects.
// All objects returned here must be treated as read-only.
type HTTPScaledObjectNamespaceLister interface {
	// List lists all HTTPScaledObjects in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.HTTPScaledObject, err error)
	// Get retrieves the HTTPScaledObject from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.HTTPScaledObject, error)
	HTTPScaledObjectNamespaceListerExpansion
}

// hTTPScaledObjectNamespaceLister implements the HTTPScaledObjectNamespaceLister
// interface.
type hTTPScaledObjectNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.HTTPScaledObject]
}
