/*
Copyright 2020 The Flux authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/fluxcd/flagger/pkg/apis/gloogateway/v1"
	gloogatewayv1 "github.com/fluxcd/flagger/pkg/client/clientset/versioned/typed/gloogateway/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeRouteTables implements RouteTableInterface
type fakeRouteTables struct {
	*gentype.FakeClientWithList[*v1.RouteTable, *v1.RouteTableList]
	Fake *FakeGatewayV1
}

func newFakeRouteTables(fake *FakeGatewayV1, namespace string) gloogatewayv1.RouteTableInterface {
	return &fakeRouteTables{
		gentype.NewFakeClientWithList[*v1.RouteTable, *v1.RouteTableList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("routetables"),
			v1.SchemeGroupVersion.WithKind("RouteTable"),
			func() *v1.RouteTable { return &v1.RouteTable{} },
			func() *v1.RouteTableList { return &v1.RouteTableList{} },
			func(dst, src *v1.RouteTableList) { dst.ListMeta = src.ListMeta },
			func(list *v1.RouteTableList) []*v1.RouteTable { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.RouteTableList, items []*v1.RouteTable) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
