apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "podinfo.fullname" . }}
  labels:
    app: {{ template "podinfo.name" . }}
    chart: {{ template "podinfo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  maxUnavailable: {{ .Values.pdb }}
  selector:
    matchLabels:
      app: {{ template "podinfo.fullname" . }}{{ if .Values.canary.enabled }}-primary{{ end }}
