/*
Copyright The Flagger Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	"context"
	"time"

	v1beta2 "github.com/weaveworks/flagger/pkg/apis/appmesh/v1beta2"
	scheme "github.com/weaveworks/flagger/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VirtualServiceListsGetter has a method to return a VirtualServiceListInterface.
// A group's client should implement this interface.
type VirtualServiceListsGetter interface {
	VirtualServiceLists(namespace string) VirtualServiceListInterface
}

// VirtualServiceListInterface has methods to work with VirtualServiceList resources.
type VirtualServiceListInterface interface {
	Create(ctx context.Context, virtualServiceList *v1beta2.VirtualServiceList, opts v1.CreateOptions) (*v1beta2.VirtualServiceList, error)
	Update(ctx context.Context, virtualServiceList *v1beta2.VirtualServiceList, opts v1.UpdateOptions) (*v1beta2.VirtualServiceList, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta2.VirtualServiceList, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta2.VirtualServiceListList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.VirtualServiceList, err error)
	VirtualServiceListExpansion
}

// virtualServiceLists implements VirtualServiceListInterface
type virtualServiceLists struct {
	client rest.Interface
	ns     string
}

// newVirtualServiceLists returns a VirtualServiceLists
func newVirtualServiceLists(c *AppmeshV1beta2Client, namespace string) *virtualServiceLists {
	return &virtualServiceLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the virtualServiceList, and returns the corresponding virtualServiceList object, and an error if there is any.
func (c *virtualServiceLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta2.VirtualServiceList, err error) {
	result = &v1beta2.VirtualServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("virtualservicelists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VirtualServiceLists that match those selectors.
func (c *virtualServiceLists) List(ctx context.Context, opts v1.ListOptions) (result *v1beta2.VirtualServiceListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta2.VirtualServiceListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("virtualservicelists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested virtualServiceLists.
func (c *virtualServiceLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("virtualservicelists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a virtualServiceList and creates it.  Returns the server's representation of the virtualServiceList, and an error, if there is any.
func (c *virtualServiceLists) Create(ctx context.Context, virtualServiceList *v1beta2.VirtualServiceList, opts v1.CreateOptions) (result *v1beta2.VirtualServiceList, err error) {
	result = &v1beta2.VirtualServiceList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("virtualservicelists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualServiceList).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a virtualServiceList and updates it. Returns the server's representation of the virtualServiceList, and an error, if there is any.
func (c *virtualServiceLists) Update(ctx context.Context, virtualServiceList *v1beta2.VirtualServiceList, opts v1.UpdateOptions) (result *v1beta2.VirtualServiceList, err error) {
	result = &v1beta2.VirtualServiceList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("virtualservicelists").
		Name(virtualServiceList.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(virtualServiceList).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the virtualServiceList and deletes it. Returns an error if one occurs.
func (c *virtualServiceLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("virtualservicelists").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *virtualServiceLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("virtualservicelists").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched virtualServiceList.
func (c *virtualServiceLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta2.VirtualServiceList, err error) {
	result = &v1beta2.VirtualServiceList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("virtualservicelists").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
