/*
Copyright The Flagger Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/weaveworks/flagger/pkg/apis/flagger/v1beta1"
	scheme "github.com/weaveworks/flagger/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MetricTemplatesGetter has a method to return a MetricTemplateInterface.
// A group's client should implement this interface.
type MetricTemplatesGetter interface {
	MetricTemplates(namespace string) MetricTemplateInterface
}

// MetricTemplateInterface has methods to work with MetricTemplate resources.
type MetricTemplateInterface interface {
	Create(*v1beta1.MetricTemplate) (*v1beta1.MetricTemplate, error)
	Update(*v1beta1.MetricTemplate) (*v1beta1.MetricTemplate, error)
	UpdateStatus(*v1beta1.MetricTemplate) (*v1beta1.MetricTemplate, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.MetricTemplate, error)
	List(opts v1.ListOptions) (*v1beta1.MetricTemplateList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MetricTemplate, err error)
	MetricTemplateExpansion
}

// metricTemplates implements MetricTemplateInterface
type metricTemplates struct {
	client rest.Interface
	ns     string
}

// newMetricTemplates returns a MetricTemplates
func newMetricTemplates(c *FlaggerV1beta1Client, namespace string) *metricTemplates {
	return &metricTemplates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the metricTemplate, and returns the corresponding metricTemplate object, and an error if there is any.
func (c *metricTemplates) Get(name string, options v1.GetOptions) (result *v1beta1.MetricTemplate, err error) {
	result = &v1beta1.MetricTemplate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("metrictemplates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MetricTemplates that match those selectors.
func (c *metricTemplates) List(opts v1.ListOptions) (result *v1beta1.MetricTemplateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.MetricTemplateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("metrictemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested metricTemplates.
func (c *metricTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("metrictemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a metricTemplate and creates it.  Returns the server's representation of the metricTemplate, and an error, if there is any.
func (c *metricTemplates) Create(metricTemplate *v1beta1.MetricTemplate) (result *v1beta1.MetricTemplate, err error) {
	result = &v1beta1.MetricTemplate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("metrictemplates").
		Body(metricTemplate).
		Do().
		Into(result)
	return
}

// Update takes the representation of a metricTemplate and updates it. Returns the server's representation of the metricTemplate, and an error, if there is any.
func (c *metricTemplates) Update(metricTemplate *v1beta1.MetricTemplate) (result *v1beta1.MetricTemplate, err error) {
	result = &v1beta1.MetricTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("metrictemplates").
		Name(metricTemplate.Name).
		Body(metricTemplate).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *metricTemplates) UpdateStatus(metricTemplate *v1beta1.MetricTemplate) (result *v1beta1.MetricTemplate, err error) {
	result = &v1beta1.MetricTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("metrictemplates").
		Name(metricTemplate.Name).
		SubResource("status").
		Body(metricTemplate).
		Do().
		Into(result)
	return
}

// Delete takes name of the metricTemplate and deletes it. Returns an error if one occurs.
func (c *metricTemplates) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("metrictemplates").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *metricTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("metrictemplates").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched metricTemplate.
func (c *metricTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MetricTemplate, err error) {
	result = &v1beta1.MetricTemplate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("metrictemplates").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
