/*
Copyright 2020 The Flux authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/fluxcd/flagger/pkg/apis/http/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterHTTPScalingSets implements ClusterHTTPScalingSetInterface
type FakeClusterHTTPScalingSets struct {
	Fake *FakeHttpV1alpha1
	ns   string
}

var clusterhttpscalingsetsResource = v1alpha1.SchemeGroupVersion.WithResource("clusterhttpscalingsets")

var clusterhttpscalingsetsKind = v1alpha1.SchemeGroupVersion.WithKind("ClusterHTTPScalingSet")

// Get takes name of the clusterHTTPScalingSet, and returns the corresponding clusterHTTPScalingSet object, and an error if there is any.
func (c *FakeClusterHTTPScalingSets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterHTTPScalingSet, err error) {
	emptyResult := &v1alpha1.ClusterHTTPScalingSet{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(clusterhttpscalingsetsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ClusterHTTPScalingSet), err
}

// List takes label and field selectors, and returns the list of ClusterHTTPScalingSets that match those selectors.
func (c *FakeClusterHTTPScalingSets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterHTTPScalingSetList, err error) {
	emptyResult := &v1alpha1.ClusterHTTPScalingSetList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(clusterhttpscalingsetsResource, clusterhttpscalingsetsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterHTTPScalingSetList{ListMeta: obj.(*v1alpha1.ClusterHTTPScalingSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterHTTPScalingSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterHTTPScalingSets.
func (c *FakeClusterHTTPScalingSets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(clusterhttpscalingsetsResource, c.ns, opts))

}

// Create takes the representation of a clusterHTTPScalingSet and creates it.  Returns the server's representation of the clusterHTTPScalingSet, and an error, if there is any.
func (c *FakeClusterHTTPScalingSets) Create(ctx context.Context, clusterHTTPScalingSet *v1alpha1.ClusterHTTPScalingSet, opts v1.CreateOptions) (result *v1alpha1.ClusterHTTPScalingSet, err error) {
	emptyResult := &v1alpha1.ClusterHTTPScalingSet{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(clusterhttpscalingsetsResource, c.ns, clusterHTTPScalingSet, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ClusterHTTPScalingSet), err
}

// Update takes the representation of a clusterHTTPScalingSet and updates it. Returns the server's representation of the clusterHTTPScalingSet, and an error, if there is any.
func (c *FakeClusterHTTPScalingSets) Update(ctx context.Context, clusterHTTPScalingSet *v1alpha1.ClusterHTTPScalingSet, opts v1.UpdateOptions) (result *v1alpha1.ClusterHTTPScalingSet, err error) {
	emptyResult := &v1alpha1.ClusterHTTPScalingSet{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(clusterhttpscalingsetsResource, c.ns, clusterHTTPScalingSet, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ClusterHTTPScalingSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterHTTPScalingSets) UpdateStatus(ctx context.Context, clusterHTTPScalingSet *v1alpha1.ClusterHTTPScalingSet, opts v1.UpdateOptions) (result *v1alpha1.ClusterHTTPScalingSet, err error) {
	emptyResult := &v1alpha1.ClusterHTTPScalingSet{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(clusterhttpscalingsetsResource, "status", c.ns, clusterHTTPScalingSet, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ClusterHTTPScalingSet), err
}

// Delete takes name of the clusterHTTPScalingSet and deletes it. Returns an error if one occurs.
func (c *FakeClusterHTTPScalingSets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(clusterhttpscalingsetsResource, c.ns, name, opts), &v1alpha1.ClusterHTTPScalingSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterHTTPScalingSets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(clusterhttpscalingsetsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterHTTPScalingSetList{})
	return err
}

// Patch applies the patch and returns the patched clusterHTTPScalingSet.
func (c *FakeClusterHTTPScalingSets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterHTTPScalingSet, err error) {
	emptyResult := &v1alpha1.ClusterHTTPScalingSet{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(clusterhttpscalingsetsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ClusterHTTPScalingSet), err
}
