//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Flux authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	gatewayv1 "github.com/fluxcd/flagger/pkg/apis/gloo/gateway/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CallCredentials) DeepCopyInto(out *CallCredentials) {
	*out = *in
	if in.FileCredentialSource != nil {
		in, out := &in.FileCredentialSource, &out.FileCredentialSource
		*out = new(CallCredentials_FileCredentialSource)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CallCredentials.
func (in *CallCredentials) DeepCopy() *CallCredentials {
	if in == nil {
		return nil
	}
	out := new(CallCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CallCredentials_FileCredentialSource) DeepCopyInto(out *CallCredentials_FileCredentialSource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CallCredentials_FileCredentialSource.
func (in *CallCredentials_FileCredentialSource) DeepCopy() *CallCredentials_FileCredentialSource {
	if in == nil {
		return nil
	}
	out := new(CallCredentials_FileCredentialSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CircuitBreakerConfig) DeepCopyInto(out *CircuitBreakerConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CircuitBreakerConfig.
func (in *CircuitBreakerConfig) DeepCopy() *CircuitBreakerConfig {
	if in == nil {
		return nil
	}
	out := new(CircuitBreakerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionConfig) DeepCopyInto(out *ConnectionConfig) {
	*out = *in
	if in.TcpKeepalive != nil {
		in, out := &in.TcpKeepalive, &out.TcpKeepalive
		*out = new(ConnectionConfig_TcpKeepAlive)
		**out = **in
	}
	if in.CommonHttpProtocolOptions != nil {
		in, out := &in.CommonHttpProtocolOptions, &out.CommonHttpProtocolOptions
		*out = new(ConnectionConfig_HttpProtocolOptions)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionConfig.
func (in *ConnectionConfig) DeepCopy() *ConnectionConfig {
	if in == nil {
		return nil
	}
	out := new(ConnectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionConfig_HttpProtocolOptions) DeepCopyInto(out *ConnectionConfig_HttpProtocolOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionConfig_HttpProtocolOptions.
func (in *ConnectionConfig_HttpProtocolOptions) DeepCopy() *ConnectionConfig_HttpProtocolOptions {
	if in == nil {
		return nil
	}
	out := new(ConnectionConfig_HttpProtocolOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionConfig_TcpKeepAlive) DeepCopyInto(out *ConnectionConfig_TcpKeepAlive) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionConfig_TcpKeepAlive.
func (in *ConnectionConfig_TcpKeepAlive) DeepCopy() *ConnectionConfig_TcpKeepAlive {
	if in == nil {
		return nil
	}
	out := new(ConnectionConfig_TcpKeepAlive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeUpstream) DeepCopyInto(out *KubeUpstream) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeUpstream.
func (in *KubeUpstream) DeepCopy() *KubeUpstream {
	if in == nil {
		return nil
	}
	out := new(KubeUpstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfig) DeepCopyInto(out *LoadBalancerConfig) {
	*out = *in
	if in.RoundRobin != nil {
		in, out := &in.RoundRobin, &out.RoundRobin
		*out = new(LoadBalancerConfigRoundRobin)
		(*in).DeepCopyInto(*out)
	}
	if in.LeastRequest != nil {
		in, out := &in.LeastRequest, &out.LeastRequest
		*out = new(LoadBalancerConfigLeastRequest)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfig.
func (in *LoadBalancerConfig) DeepCopy() *LoadBalancerConfig {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfigLeastRequest) DeepCopyInto(out *LoadBalancerConfigLeastRequest) {
	*out = *in
	if in.SlowStartConfig != nil {
		in, out := &in.SlowStartConfig, &out.SlowStartConfig
		*out = new(SlowStartConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfigLeastRequest.
func (in *LoadBalancerConfigLeastRequest) DeepCopy() *LoadBalancerConfigLeastRequest {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfigLeastRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfigRoundRobin) DeepCopyInto(out *LoadBalancerConfigRoundRobin) {
	*out = *in
	if in.SlowStartConfig != nil {
		in, out := &in.SlowStartConfig, &out.SlowStartConfig
		*out = new(SlowStartConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfigRoundRobin.
func (in *LoadBalancerConfigRoundRobin) DeepCopy() *LoadBalancerConfigRoundRobin {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfigRoundRobin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlowStartConfig) DeepCopyInto(out *SlowStartConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlowStartConfig.
func (in *SlowStartConfig) DeepCopy() *SlowStartConfig {
	if in == nil {
		return nil
	}
	out := new(SlowStartConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SslParameters) DeepCopyInto(out *SslParameters) {
	*out = *in
	if in.CipherSuites != nil {
		in, out := &in.CipherSuites, &out.CipherSuites
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EcdhCurves != nil {
		in, out := &in.EcdhCurves, &out.EcdhCurves
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SslParameters.
func (in *SslParameters) DeepCopy() *SslParameters {
	if in == nil {
		return nil
	}
	out := new(SslParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Upstream) DeepCopyInto(out *Upstream) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Upstream.
func (in *Upstream) DeepCopy() *Upstream {
	if in == nil {
		return nil
	}
	out := new(Upstream)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Upstream) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamList) DeepCopyInto(out *UpstreamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Upstream, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamList.
func (in *UpstreamList) DeepCopy() *UpstreamList {
	if in == nil {
		return nil
	}
	out := new(UpstreamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpstreamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSpec) DeepCopyInto(out *UpstreamSpec) {
	*out = *in
	if in.Kube != nil {
		in, out := &in.Kube, &out.Kube
		*out = new(KubeUpstream)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SslConfig != nil {
		in, out := &in.SslConfig, &out.SslConfig
		*out = new(UpstreamSslConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CircuitBreakers != nil {
		in, out := &in.CircuitBreakers, &out.CircuitBreakers
		*out = new(CircuitBreakerConfig)
		**out = **in
	}
	if in.ConnectionConfig != nil {
		in, out := &in.ConnectionConfig, &out.ConnectionConfig
		*out = new(ConnectionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LoadBalancerConfig != nil {
		in, out := &in.LoadBalancerConfig, &out.LoadBalancerConfig
		*out = new(LoadBalancerConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSpec.
func (in *UpstreamSpec) DeepCopy() *UpstreamSpec {
	if in == nil {
		return nil
	}
	out := new(UpstreamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSslConfig) DeepCopyInto(out *UpstreamSslConfig) {
	*out = *in
	if in.VerifySubjectAltName != nil {
		in, out := &in.VerifySubjectAltName, &out.VerifySubjectAltName
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(SslParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.AlpnProtocols != nil {
		in, out := &in.AlpnProtocols, &out.AlpnProtocols
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UpstreamSslConfig_Sds != nil {
		in, out := &in.UpstreamSslConfig_Sds, &out.UpstreamSslConfig_Sds
		*out = new(UpstreamSslConfig_Sds)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(gatewayv1.ResourceRef)
		**out = **in
	}
	if in.UpstreamSslConfig_SslFiles != nil {
		in, out := &in.UpstreamSslConfig_SslFiles, &out.UpstreamSslConfig_SslFiles
		*out = new(UpstreamSslConfig_SslFiles)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSslConfig.
func (in *UpstreamSslConfig) DeepCopy() *UpstreamSslConfig {
	if in == nil {
		return nil
	}
	out := new(UpstreamSslConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSslConfig_Sds) DeepCopyInto(out *UpstreamSslConfig_Sds) {
	*out = *in
	if in.CallCredentials != nil {
		in, out := &in.CallCredentials, &out.CallCredentials
		*out = new(CallCredentials)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSslConfig_Sds.
func (in *UpstreamSslConfig_Sds) DeepCopy() *UpstreamSslConfig_Sds {
	if in == nil {
		return nil
	}
	out := new(UpstreamSslConfig_Sds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamSslConfig_SslFiles) DeepCopyInto(out *UpstreamSslConfig_SslFiles) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamSslConfig_SslFiles.
func (in *UpstreamSslConfig_SslFiles) DeepCopy() *UpstreamSslConfig_SslFiles {
	if in == nil {
		return nil
	}
	out := new(UpstreamSslConfig_SslFiles)
	in.DeepCopyInto(out)
	return out
}
