# Default values for appmesh-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
discovery:
  # discovery.optIn `true` if only services with the 'expose' annotation are discoverable
  optIn: true

proxy:
  access_log_path: /dev/null
  image:
    repository: docker.io/envoyproxy/envoy
    tag: v1.12.0
    pullPolicy: IfNotPresent

controller:
  image:
    repository: weaveworks/flagger-appmesh-gateway
    tag: v1.1.0
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  # service.type: When set to LoadBalancer it creates an AWS NLB
  type: LoadBalancer
  port: 80

hpa:
  # hpa.enabled `true` if HPA resource should be created, metrics-server is required
  enabled: true
  maxReplicas: 3
  # hpa.cpu average total CPU usage per pod (1-100)
  cpu: 99
  # hpa.memory average memory usage per pod (100Mi-1Gi)
  memory:

resources:
  limits:
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

serviceAccount:
  # serviceAccount.create: Whether to create a service account or not
  create: true
  # serviceAccount.name: The name of the service account to create or use
  name: ""

rbac:
  # rbac.create: `true` if rbac resources should be created
  create: true
  # rbac.pspEnabled: `true` if PodSecurityPolicy resources should be created
  pspEnabled: false

mesh:
  # mesh.create: `true` if mesh resource should be created
  create: false
  # mesh.name: The name of the mesh to use
  name: "global"
  # mesh.discovery: The service discovery type to use, can be dns or cloudmap
  discovery: dns
