{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "flagger.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "flagger.name" . }}
{{- end }}
