{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ include "capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "loadtester.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "loadtester.name" . }}
{{- end }}
