/*
Copyright 2020 The Flux authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	istiov1beta1 "github.com/fluxcd/flagger/pkg/apis/istio/v1beta1"
	scheme "github.com/fluxcd/flagger/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DestinationRulesGetter has a method to return a DestinationRuleInterface.
// A group's client should implement this interface.
type DestinationRulesGetter interface {
	DestinationRules(namespace string) DestinationRuleInterface
}

// DestinationRuleInterface has methods to work with DestinationRule resources.
type DestinationRuleInterface interface {
	Create(ctx context.Context, destinationRule *istiov1beta1.DestinationRule, opts v1.CreateOptions) (*istiov1beta1.DestinationRule, error)
	Update(ctx context.Context, destinationRule *istiov1beta1.DestinationRule, opts v1.UpdateOptions) (*istiov1beta1.DestinationRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*istiov1beta1.DestinationRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*istiov1beta1.DestinationRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *istiov1beta1.DestinationRule, err error)
	DestinationRuleExpansion
}

// destinationRules implements DestinationRuleInterface
type destinationRules struct {
	*gentype.ClientWithList[*istiov1beta1.DestinationRule, *istiov1beta1.DestinationRuleList]
}

// newDestinationRules returns a DestinationRules
func newDestinationRules(c *NetworkingV1beta1Client, namespace string) *destinationRules {
	return &destinationRules{
		gentype.NewClientWithList[*istiov1beta1.DestinationRule, *istiov1beta1.DestinationRuleList](
			"destinationrules",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *istiov1beta1.DestinationRule { return &istiov1beta1.DestinationRule{} },
			func() *istiov1beta1.DestinationRuleList { return &istiov1beta1.DestinationRuleList{} },
		),
	}
}
